stages:
  - build
  - test
  - report

variables:
  MYSQL_DATABASE: silla_io
  MYSQL_ROOT_PASSWORD: dbs1cret

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install git libcurl4-gnutls-dev libjpeg-dev libpng-dev zlib1g-dev libfreetype6-dev libsqlite3-dev libpcre3-dev -yqq

  # Compile PHP, include these extensions.
  - docker-php-ext-install mbstring pdo_mysql curl json gd zip

  # Install Composer and project dependencies.
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

  # Run database create
  - php ./silla tasks:db:create resources/db/mysql/dump.mysql.sql

# Build stage jobs

build:php5.6:
  image: php:5.6
  stage: build
  script:
    - php composer.phar require --dev jakub-onderka/php-parallel-lint
    - ./vendor/bin/parallel-lint --exclude vendor .
    - php composer.phar require --dev squizlabs/php_codesniffer:2.9.0
    - ./vendor/bin/phpcs --extensions=php --standard=PSR2 --ignore=vendor,public,temp .
  cache:
    untracked: true
  only:
    - develop
    - master

build:php7.0:
  image: php:7.0
  stage: build
  script:
    - php composer.phar require --dev jakub-onderka/php-parallel-lint
    - ./vendor/bin/parallel-lint --exclude vendor .
    - php composer.phar require --dev squizlabs/php_codesniffer:2.9.0
    - ./vendor/bin/phpcs --extensions=php --standard=PSR2 --ignore=vendor,public,temp .
  cache:
    untracked: true
  only:
    - develop
    - master

build:php-latest:
  image: php:latest
  stage: build
  script:
    - php composer.phar require --dev jakub-onderka/php-parallel-lint
    - ./vendor/bin/parallel-lint --exclude vendor .
    - php composer.phar require --dev squizlabs/php_codesniffer:2.9.0
    - ./vendor/bin/phpcs --extensions=php --standard=PSR2 --ignore=vendor,public,temp .
  cache:
    untracked: true
  only:
    - develop
    - master

# Test Stage jobs
test:php5.6:mysql5.6:
  image: php:5.6
  stage: test
  dependencies:
    - build:php5.6
  services:
    - mysql:5.6
  script:
    - ./vendor/bin/phpunit --stderr --configuration ./build/configurations/phpunit.xml
  only:
    - develop
    - master

test:php7.0:mysql5.7:
  image: php:7.0
  stage: test
  dependencies:
    - build:php7.0
  services:
    - mysql:5.7
  script:
    - ./vendor/bin/phpunit --stderr --configuration ./build/configurations/phpunit.xml
  only:
    - develop
    - master

test:php-latest:mysql-latest:
  image: php:latest
  stage: test
  dependencies:
    - build:php-latest
  services:
    - mysql:latest
  script:
    - ./vendor/bin/phpunit --stderr --configuration ./build/configurations/phpunit.xml
  only:
    - develop
    - master

report:php5.6:
  image: php:5.6
  stage: report
  allow_failure: true
  dependencies:
      - build:php-latest
      - test:php5.6:mysql5.6
  script:
    - php composer.phar require --dev apigen/apigen:v4.1.2
    - ./vendor/bin/apigen generate --quiet --config ./build/configurations/apigen.yaml
    - php composer.phar require --dev phploc/phploc
    - ./vendor/bin/phploc --exclude vendor --exclude temp --exclude public --count-tests --log-csv ./build/logs/phploc.csv --log-xml ./build/logs/phploc.xml .
    - php composer.phar require --dev phpmd/phpmd
    - ./vendor/bin/phpmd . html codesize --reportfile build/logs/pmd.html --exclude vendor,tests,temp,public
    - php composer.phar require --dev pdepend/pdepend
    - ./vendor/bin/pdepend --jdepend-xml=build/logs/pdepend-jdepend.xml --jdepend-chart=build/logs/pdepend-dependencies.svg --overview-pyramid=build/logs/pdepend-overview-pyramid.svg --ignore=vendor,public,resources,temp .
    - php composer.phar require --dev sebastian/phpcpd
    - ./vendor/bin/phpcpd --log-pmd build/logs/pmd-cpd.xml --exclude vendor --exclude temp --exclude public .
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - ./public/doc/
      - ./build/logs/
    expires_in: 1 week
  cache:
    untracked: true
  only:
    - master

report:php7.0:
  image: php:7.0
  stage: report
  allow_failure: true
  dependencies:
      - build:php-latest
      - test:php7.0:mysql5.7
  script:
    - php composer.phar require --dev apigen/apigen:v4.1.2
    - ./vendor/bin/apigen generate --quiet --config ./build/configurations/apigen.yaml
    - php composer.phar require --dev phploc/phploc
    - ./vendor/bin/phploc --exclude vendor --exclude temp --exclude public --count-tests --log-csv ./build/logs/phploc.csv --log-xml ./build/logs/phploc.xml .
    - php composer.phar require --dev phpmd/phpmd
    - ./vendor/bin/phpmd . html codesize --reportfile build/logs/pmd.html --exclude vendor,tests,temp,public
    - php composer.phar require --dev pdepend/pdepend
    - ./vendor/bin/pdepend --jdepend-xml=build/logs/pdepend-jdepend.xml --jdepend-chart=build/logs/pdepend-dependencies.svg --overview-pyramid=build/logs/pdepend-overview-pyramid.svg --ignore=vendor,public,resources,temp .
    - php composer.phar require --dev sebastian/phpcpd
    - ./vendor/bin/phpcpd --log-pmd build/logs/pmd-cpd.xml --exclude vendor --exclude temp --exclude public .
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - ./public/doc/
      - ./build/logs/
    expires_in: 1 week
  cache:
    untracked: true
  only:
    - master

report:php7.0:
  image: php:latest
  stage: report
  allow_failure: true
  dependencies:
      - build:php-latest
      - test:php-latest:mysql-latest
  script:
    - php composer.phar require --dev apigen/apigen:v4.1.2
    - ./vendor/bin/apigen generate --quiet --config ./build/configurations/apigen.yaml
    - php composer.phar require --dev phploc/phploc
    - ./vendor/bin/phploc --exclude vendor --exclude temp --exclude public --count-tests --log-csv ./build/logs/phploc.csv --log-xml ./build/logs/phploc.xml .
    - php composer.phar require --dev phpmd/phpmd
    - ./vendor/bin/phpmd . html codesize --reportfile build/logs/pmd.html --exclude vendor,tests,temp,public
    - php composer.phar require --dev pdepend/pdepend
    - ./vendor/bin/pdepend --jdepend-xml=build/logs/pdepend-jdepend.xml --jdepend-chart=build/logs/pdepend-dependencies.svg --overview-pyramid=build/logs/pdepend-overview-pyramid.svg --ignore=vendor,public,resources,temp .
    - php composer.phar require --dev sebastian/phpcpd
    - ./vendor/bin/phpcpd --log-pmd build/logs/pmd-cpd.xml --exclude vendor --exclude temp --exclude public .
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - ./public/doc/
      - ./build/logs/
    expires_in: 1 week
  cache:
    untracked: true
  only:
    - master