stages:
  - build
  - test
  - report

variables:
  ENV_SILLA_ENVIRONMENT: ci
  MYSQL_DATABASE: silla_io
  MYSQL_ROOT_PASSWORD: dbs1cret

before_script:
  # Install Composer
  - curl -sS https://getcomposer.org/installer | php

# Build stage jobs

build:php5.6:
  image: weareathlon/silla.io:struma-php5.6
  stage: build
  script:
    - COMPOSER=composer.build.json php composer.phar require jakub-onderka/php-parallel-lint
    - ./vendor/bin/parallel-lint --exclude vendor .
    - COMPOSER=composer.build.json php composer.phar require squizlabs/php_codesniffer:2.9.0
    - ./vendor/bin/phpcs --extensions=php --standard=PSR2 --ignore=vendor,public,temp .
  only:
    - develop
    - master

build:php7.0:
  image: weareathlon/silla.io:struma-php7.0
  stage: build
  script:
    - COMPOSER=composer.build.json php composer.phar require jakub-onderka/php-parallel-lint
    - ./vendor/bin/parallel-lint --exclude vendor .
    - COMPOSER=composer.build.json php composer.phar require squizlabs/php_codesniffer:2.9.0
    - ./vendor/bin/phpcs --extensions=php --standard=PSR2 --ignore=vendor,public,temp .
  only:
    - develop
    - master

build:php-latest:
  image: weareathlon/silla.io:latest
  stage: build
  script:
    - COMPOSER=composer.build.json php composer.phar require jakub-onderka/php-parallel-lint
    - ./vendor/bin/parallel-lint --exclude vendor .
    - COMPOSER=composer.build.json php composer.phar require squizlabs/php_codesniffer:2.9.0
    - ./vendor/bin/phpcs --extensions=php --standard=PSR2 --ignore=vendor,public,temp .
  only:
    - develop
    - master

# Test stage jobs

.test:php5.6:mysql5.6:
  image: weareathlon/silla.io:struma-php5.6
  stage: test
  dependencies:
    - build:php5.6
  services:
    - mysql:5.6
    - redis:latest
  script:
    - php composer.phar install
    - ./silla tasks:db:create ./resources/db/mysql/dump.mysql.sql
    - ./vendor/bin/phpunit --stderr --coverage-text --colors=never --configuration ./build/configurations/phpunit.xml
  only:
    - develop
    - master

test:php7.0:mysql5.7:
  image: weareathlon/silla.io:struma-php7.0
  stage: test
  dependencies:
    - build:php7.0
  services:
    - mysql:5.7
    - redis:latest
  script:
    - php composer.phar install
    - ./silla tasks:db:create ./resources/db/mysql/dump.mysql.sql
    - ./vendor/bin/phpunit --stderr --coverage-text --colors=never --configuration ./build/configurations/phpunit.xml
  only:
    - develop
    - master

test:php-latest:mysql-latest:
  image: weareathlon/silla.io:latest
  stage: test
  dependencies:
    - build:php-latest
  services:
    - mysql:latest
    - redis:latest
  script:
    - php composer.phar install
    - ./silla tasks:db:create ./resources/db/mysql/dump.mysql.sql
    - ./vendor/bin/phpunit --stderr --coverage-text --colors=never --configuration ./build/configurations/phpunit.xml
  only:
    - develop
    - master

# Report stage jobs

.report:php5.6:
  image: weareathlon/silla.io:struma-php5.6
  stage: report
  allow_failure: true
  dependencies:
      - build:php5.6
      - test:php5.6:mysql5.6
  script:
    - COMPOSER=composer.report.json php composer.phar require apigen/apigen:v4.1.2
    - ./vendor/bin/apigen generate --quiet --config ./build/configurations/apigen.yaml
    - COMPOSER=composer.report.json php composer.phar require phploc/phploc:@stable
    - ./vendor/bin/phploc --exclude vendor --exclude temp --exclude public --count-tests --log-csv ./build/logs/phploc.csv --log-xml ./build/logs/phploc.xml .
    - COMPOSER=composer.report.json php composer.phar require phpmd/phpmd:@stable
    - ./vendor/bin/phpmd . html codesize --reportfile build/logs/pmd.html --exclude vendor,tests,temp,public --ignore-violations-on-exit
    - COMPOSER=composer.report.json php composer.phar require pdepend/pdepend:@stable
    - ./vendor/bin/pdepend --jdepend-xml=build/logs/pdepend-jdepend.xml --jdepend-chart=build/logs/pdepend-dependencies.svg --overview-pyramid=build/logs/pdepend-overview-pyramid.svg --ignore=vendor,public,resources,temp .
#   - COMPOSER=composer.report.json php composer.phar require sebastian/phpcpd:@stable
#   - ./vendor/bin/phpcpd --log-pmd build/logs/pmd-cpd.xml --exclude vendor --exclude temp --exclude public .
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - ./public/doc/
      - ./build/logs/
    expire_in: 1 week
  only:
    - master

report:php7.0:
  image: weareathlon/silla.io:struma-php7.0
  stage: report
  allow_failure: true
  dependencies:
      - build:php7.0
      - test:php7.0:mysql5.7
  script:
    - COMPOSER=composer.report.json php composer.phar require apigen/apigen:v4.1.2
    - ./vendor/bin/apigen generate --quiet --config ./build/configurations/apigen.yaml
    - COMPOSER=composer.report.json php composer.phar require phploc/phploc:@stable
    - ./vendor/bin/phploc --exclude vendor --exclude temp --exclude public --count-tests --log-csv ./build/logs/phploc.csv --log-xml ./build/logs/phploc.xml .
    - COMPOSER=composer.report.json php composer.phar require phpmd/phpmd:@stable
    - ./vendor/bin/phpmd . html codesize --reportfile build/logs/pmd.html --exclude vendor,tests,temp,public --ignore-violations-on-exit
    - COMPOSER=composer.report.json php composer.phar require pdepend/pdepend:@stable
    - ./vendor/bin/pdepend --jdepend-xml=build/logs/pdepend-jdepend.xml --jdepend-chart=build/logs/pdepend-dependencies.svg --overview-pyramid=build/logs/pdepend-overview-pyramid.svg --ignore=vendor,public,resources,temp .
#   - COMPOSER=composer.report.json php composer.phar require sebastian/phpcpd:@stable
#   - ./vendor/bin/phpcpd --log-pmd build/logs/pmd-cpd.xml --exclude vendor --exclude temp --exclude public .
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - ./public/doc/
      - ./build/logs/
    expire_in: 1 week
  only:
    - master

report:php-latest:
  image: weareathlon/silla.io:latest
  stage: report
  allow_failure: true
  dependencies:
      - build:php-latest
      - test:php-latest:mysql-latest
  script:
    - COMPOSER=composer.report.json php composer.phar require apigen/apigen:v4.1.2
    - ./vendor/bin/apigen generate --quiet --config ./build/configurations/apigen.yaml
    - COMPOSER=composer.report.json php composer.phar require phploc/phploc:@stable
    - ./vendor/bin/phploc --exclude vendor --exclude temp --exclude public --count-tests --log-csv ./build/logs/phploc.csv --log-xml ./build/logs/phploc.xml .
    - COMPOSER=composer.report.json php composer.phar require phpmd/phpmd:@stable
    - ./vendor/bin/phpmd . html codesize --reportfile build/logs/pmd.html --exclude vendor,tests,temp,public --ignore-violations-on-exit
    - COMPOSER=composer.report.json php composer.phar require pdepend/pdepend:@stable
    - ./vendor/bin/pdepend --jdepend-xml=build/logs/pdepend-jdepend.xml --jdepend-chart=build/logs/pdepend-dependencies.svg --overview-pyramid=build/logs/pdepend-overview-pyramid.svg --ignore=vendor,public,resources,temp .
#   - COMPOSER=composer.report.json php composer.phar require sebastian/phpcpd:@stable
#   - ./vendor/bin/phpcpd --log-pmd build/logs/pmd-cpd.xml --exclude vendor --exclude temp --exclude public .
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - ./public/doc/
      - ./build/logs/
    expire_in: 1 week
  only:
    - master