#!/usr/bin/env php
<?php
/**
 * Silla.IO CLI Task Manager.
 *
 * @package    Silla.IO
 * @subpackage Core
 * @author     Kalin Stefanov <kalin@athlonsofia.com>
 * @copyright  Copyright (c) 2015, Silla.io
 * @license    http://opensource.org/licenses/GPL-3.0 GNU General Public License, version 3.0 (GPLv3)
 */

namespace Core;

use Core\CLI;

$currentDir = __DIR__;

require_once $currentDir . DIRECTORY_SEPARATOR . 'core' . DIRECTORY_SEPARATOR . 'boot.php';

if ($argc > 1) {
    $parts = explode(':', $argv[1]);
    $command = implode(':', array_slice($parts, 1));
    $class = 'Core\CLI\\' . $parts[0];

    if ('db' === $command) {
        $migrations = array_map(function ($item) {
            $name = substr($item, 0, -4);

            return array(
                'name' => $name,
                'version' => substr($name, -10)
            );
        }, array_slice(
            scandir(Config()->paths('root') . 'db' . DIRECTORY_SEPARATOR . 'migrations' . DIRECTORY_SEPARATOR),
            2
        ));

        usort($migrations, function ($a, $b) {
            return $a['version'] < $b['version'];
        });

        CLI\DB::$migrations = $migrations;
    } elseif ('generate' === $command) {
        call_user_func_array(array($class, $command), array_slice($argv, 2));
    } else {
        if (!class_exists($class)) {
            $class = 'Core\CLI\\' . implode('\\', $parts);
        }

        if (!class_exists($class)) {
            $class = '\\' . implode('\\', $parts);
        }

        if (method_exists($class, 'init')) {
            call_user_func_array(array($class, 'init'), array_slice($argv, 2));
        }

        call_user_func_array(array($class, 'run'), array_slice($argv, 2));
    }
}
