<?php
return array(
    'general'     => array(
        'meta'   => array(
            'serialize' => false,
            'dynamic'   => false,
        ),
        'fields' => array(
            'current_password' => array(
                'type'        => 'password',
                'filter'      => false,
                'list'        => false,
                'export'      => false,
                'readonly'    => false,
                'caption'     => true,
                'hidden'      => true,
                'validations' => array(
                    'length' => 100,
                    'format' => '/[e+]/',
                ),
            ),
            'avatar'           => array(
                'type'        => 'custom',
                'filter'      => false,
                'list'        => true,
                'export'      => false,
                'readonly'    => true,
                'sort'        => false,
                'caption'     => false,
                'hidden'      => false,
                'validations' => array(),
            ),
            'name'             => array(
                'type'        => 'text',
                'filter'      => true,
                'list'        => true,
                'export'      => true,
                'readonly'    => false,
                'sort'        => true,
                'caption'     => true,
                'hidden'      => false,
                'validations' => array(),
            ),
            'role_id'          => array(
                'type'        => 'select',
                'filter'      => true,
                'list'        => true,
                'export'      => true,
                'readonly'    => false,
                'sort'        => true,
                'caption'     => true,
                'hidden'      => false,
                'validations' => array(),
            ),
            'email'            => array(
                'type'        => 'email',
                'filter'      => false,
                'list'        => false,
                'export'      => true,
                'readonly'    => false,
                'sort'        => true,
                'caption'     => true,
                'hidden'      => false,
                'validations' => array(),
            ),
            'login_on'         => array(
                'type'        => 'datetime',
                'filter'      => true,
                'list'        => true,
                'export'      => true,
                'readonly'    => false,
                'sort'        => true,
                'caption'     => true,
                'hidden'      => false,
                'validations' => array(),
            ),
            'created_on'       => array(
                'type'        => 'datetime',
                'filter'      => true,
                'list'        => true,
                'export'      => true,
                'readonly'    => false,
                'sort'        => true,
                'caption'     => true,
                'hidden'      => false,
                'validations' => array(),
            ),
            'updated_on'       => array(
                'type'        => 'datetime',
                'filter'      => false,
                'list'        => false,
                'export'      => true,
                'readonly'    => false,
                'sort'        => true,
                'caption'     => true,
                'hidden'      => false,
                'validations' => array(),
            ),
        ),
    ),
    'credentials' => array(
        'meta'   => array(
            'serialize' => false,
            'dynamic'   => false,
        ),
        'fields' => array(
            'current_password' => array(
                'type'        => 'password',
                'filter'      => false,
                'list'        => false,
                'export'      => false,
                'readonly'    => false,
                'caption'     => true,
                'hidden'      => true,
                'validations' => array(
                    'length' => 100,
                ),
            ),
            'password'         => array(
                'type'        => 'password',
                'filter'      => false,
                'list'        => false,
                'export'      => false,
                'readonly'    => false,
                'caption'     => true,
                'hidden'      => true,
                'validations' => array(
                    'length' => 100,
                ),
            ),
            'password_confirm' => array(
                'type'        => 'password',
                'filter'      => false,
                'list'        => false,
                'export'      => false,
                'readonly'    => false,
                'caption'     => true,
                'hidden'      => true,
                'validations' => array(
                    'length' => 100,
                ),
            ),
        ),
    ),
    'settings'    => array(
        'meta'   => array(
            'serialize' => false,
            'dynamic'   => false,
        ),
        'fields' => array(
            'timezone' => array(
                'type'        => 'timezone',
                'filter'      => false,
                'list'        => false,
                'export'      => true,
                'readonly'    => false,
                'caption'     => true,
                'hidden'      => false,
                'validations' => array(),
            ),
        ),
    ),
);
