# Routes

# Home
- route: /
  maps:
    controller: app
    action    : index

- route: /:controller
  maps:
    controller: *
    action    : index

# Default Route
- route: /:controller/:action
  maps:
    controller: *
    action    : *